# Generated by Django 5.2.6 on 2025-10-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangJeongDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='행정동 이름', max_length=100, unique=True)),
                ('population', models.IntegerField(blank=True, help_text='거주 인구 수', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(help_text='API에서 사용하는 정류장 고유 ID', max_length=20, unique=True)),
                ('name', models.CharField(help_text='정류장 이름', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='정류장 경도 (Longitude)', max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='정류장 위도 (Latitude)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='정류장 활성화 여부')),
                ('district', models.ForeignKey(blank=True, help_text='정류장이 속한 행정동', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.hangjeongdong')),
            ],
        ),
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='데이터 수집 시간')),
                ('passengers_on', models.IntegerField(help_text='승차 인원')),
                ('passengers_off', models.IntegerField(help_text='하차 인원')),
                ('bus_frequency', models.IntegerField(help_text='버스 운행 횟수')),
                ('bus_stop', models.ForeignKey(help_text='대상 버스 정류장', on_delete=django.db.models.deletion.CASCADE, to='main.busstop')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('bus_stop', 'timestamp')},
            },
        ),
    ]
