# Generated by Django 5.2.7 on 2025-10-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(help_text='노선 ID', max_length=20)),
                ('busstop_id', models.CharField(help_text='정류장 ID', max_length=20)),
                ('timestamp', models.DateTimeField(help_text='데이터 수집 시간')),
                ('passengers_on', models.IntegerField(help_text='승차 인원')),
                ('passengers_off', models.IntegerField(help_text='하차 인원')),
            ],
            options={
                'ordering': ['-timestamp', 'bus_id', 'busstop_id'],
            },
        ),
        migrations.CreateModel(
            name='BusDataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(help_text='노선 ID', max_length=20)),
                ('busstop_id', models.CharField(help_text='정류장 ID', max_length=20)),
                ('timestamp', models.DateTimeField(help_text='데이터 기준 시간')),
                ('passengers_on', models.IntegerField(help_text='승차 인원')),
                ('passengers_off', models.IntegerField(help_text='하차 인원')),
                ('archived_at', models.DateTimeField(auto_now_add=True, help_text='데이터 보관 시점')),
            ],
            options={
                'ordering': ['-archived_at', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busstop_id', models.CharField(help_text='정류장 ID', max_length=20, unique=True)),
                ('name', models.CharField(help_text='정류장 이름', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='정류장 경도 (Longitude)', max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='정류장 위도 (Latitude)', max_digits=10)),
                ('district_id', models.CharField(blank=True, help_text='정류장이 속한 행정동 ID', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='정류장 활성화 여부')),
            ],
        ),
        migrations.CreateModel(
            name='BusStopHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busstop_id', models.CharField(help_text='정류장 ID', max_length=20)),
                ('name', models.CharField(help_text='정류장 이름', max_length=100)),
                ('longitude', models.DecimalField(decimal_places=7, help_text='정류장 경도 (Longitude)', max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=7, help_text='정류장 위도 (Latitude)', max_digits=10)),
                ('district_id', models.CharField(blank=True, help_text='정류장이 속한 행정동 ID', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='정류장 활성화 여부')),
                ('archived_at', models.DateTimeField(auto_now_add=True, help_text='데이터 보관 시점')),
            ],
            options={
                'ordering': ['-archived_at', 'busstop_id'],
            },
        ),
        migrations.CreateModel(
            name='HangJeongDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.CharField(help_text='행정동 ID', max_length=10, unique=True)),
                ('name', models.CharField(help_text='행정동 이름', max_length=100)),
                ('population', models.IntegerField(blank=True, help_text='총 생활 인구수', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HangJeongDongHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_id', models.CharField(help_text='행정동 ID', max_length=10)),
                ('name', models.CharField(help_text='행정동 이름', max_length=100)),
                ('population', models.IntegerField(blank=True, help_text='총 생활 인구수', null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, help_text='데이터 보관 시점')),
            ],
            options={
                'ordering': ['-archived_at', 'district_id'],
            },
        ),
    ]
